[package]
name = "pdftools"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
lopdf = "0.34.0"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "pdftools_benchmark"
harness = false
