name: Coverage

on:
  pull_request:
    branches: [ "master" ]

jobs:
  coverage:
    runs-on:
      group: runners-xl
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Dependencies
        run: sudo apt install protobuf-compiler

      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: cargo tarpaulin --out lcov --output-dir . --timeout 300
        env:
          ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
          VOYAGE_AI_API_KEY: ${{ secrets.VOYAGE_AI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_MODEL: claude-3-haiku-20240307
          OPENAI_EMBEDDING_MODEL: text-embedding-3-small
          MAX_CONCURRENT_REQUESTS: 5

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yrahul3910/zotero-rag
          files: lcov.info
          fail_ci_if_error: true
